steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.analyzer', '-t', 'gcr.io/$PROJECT_ID/analyzer-agent:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/analyzer-agent:latest']
images:
- 'gcr.io/$PROJECT_ID/analyzer-agent:latest'